# Generated by Django 4.1.6 on 2023-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='nome',
            field=models.CharField(default='E', help_text='Enterprise name', max_length=100),
        ),
    ]
