# Generated by Django 4.1.6 on 2023-02-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_enterprise_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
