# Generated by Django 4.1.6 on 2023-02-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_enterprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='enterprise',
            new_name='enterpriseE',
        ),
    ]
