# Generated by Django 4.1.6 on 2023-02-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_enterprise_employee_enterprisee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='enterpriseE',
            new_name='enterprise',
        ),
    ]
