# Generated by Django 4.1.6 on 2023-02-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department_employee_enterprise_and_more'),
        ('register_extra_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerextrahours',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
    ]
