# Generated by Django 4.1.6 on 2023-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hours', '0002_registerextrahours_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerextrahours',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
