# Generated by Django 4.1.6 on 2023-02-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documents_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='archieve',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
