# Generated by Django 4.1.7 on 2023-02-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documents_archieve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='archieve',
            new_name='archive',
        ),
    ]
