# Generated by Django 4.1.6 on 2023-02-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='enterprise.enterprise'),
            preserve_default=False,
        ),
    ]
